---
- name: Remove big size files
  command: find /var -name "*.log" \( \( -size +50M -mtime +7 \) -o -mtime +30 \) -exec truncate {} --size 0 \;

- name: Clean yum
  command: yum clean all

- name: Remove yum cache
  file:
    name: /var/cache/yum
    state: absent
