---
source_folder: '/vagrant/bpm/4.1'

installation_folder: '/vagrant/bpm_installation'

installer_archives:
  - 'TIB_amx-bpm_4.1.0_linux24gl23_x86_64.zip'

tibco_home: '/home/vagrant/tibco'
tibco_env_name: 'TIBCO-HOME'
tibco_config_home: '/home/vagrant/TIBCO_HOME'

env_name: 'amx-bpm'

beats:
  - filebeat
  - heartbeat

bpm_db_connection: "jdbc:oracle:thin:@localhost:1521/orcl.localdomain"
bpm_db_user: "bpmuser"
bpm_db_password: "bpmuser"

logstash_conf_path: /etc/logstash/conf.d
logstash_lib_path: /usr/share/logstash/lib
